// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"client/models"
)

// PutProductReader is a Reader for the PutProduct structure.
type PutProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPutProductCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /products/{id}] putProduct", response, response.Code())
	}
}

// NewPutProductCreated creates a PutProductCreated with default headers values
func NewPutProductCreated() *PutProductCreated {
	return &PutProductCreated{}
}

/*
PutProductCreated describes a response with status code 201, with default header values.

Product returns in the response
*/
type PutProductCreated struct {
	Payload *models.Product
}

// IsSuccess returns true when this put product created response has a 2xx status code
func (o *PutProductCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put product created response has a 3xx status code
func (o *PutProductCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put product created response has a 4xx status code
func (o *PutProductCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this put product created response has a 5xx status code
func (o *PutProductCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this put product created response a status code equal to that given
func (o *PutProductCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the put product created response
func (o *PutProductCreated) Code() int {
	return 201
}

func (o *PutProductCreated) Error() string {
	return fmt.Sprintf("[PUT /products/{id}][%d] putProductCreated  %+v", 201, o.Payload)
}

func (o *PutProductCreated) String() string {
	return fmt.Sprintf("[PUT /products/{id}][%d] putProductCreated  %+v", 201, o.Payload)
}

func (o *PutProductCreated) GetPayload() *models.Product {
	return o.Payload
}

func (o *PutProductCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Product)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
